name: "Setup Java & Maven"
inputs:
  JAVA_VERSION:
    required: true
    default: "17"
  MAVEN_VERSION:
    required: true
    default: "3.9.4"
runs:
  using: "composite"
  steps:
    - name: "Setup Java & Maven"
      id: setup
      run: |
        cd ${{ github.action_path }}
        chmod +x ./bin/main.sh
        ./bin/main.sh ${{ inputs.JAVA_VERSION }} ${{ inputs.MAVEN_VERSION }}
        echo "${{ github.action_path }}/env/jdk/bin" >> $GITHUB_PATH
        echo "${{ github.action_path }}/env/maven/bin" >> $GITHUB_PATH
      shell: bash
