name: "Setup Scala"
inputs:
  JAVA_VERSION:
    required: true
    default: "21.0.0"
  MAVEN_VERSION:
    required: true
    default: "3.9.4"
runs:
  using: "composite"
  steps:
    - name: "Setup Java & Maven"
      id: setup
      run: |
        cd ${{ github.action_path }}
        chmod +x ./setup.sh
        ./setup.sh ${{ inputs.JAVA_VERSION }} ${{ inputs.MAVEN_VERSION }}
        echo "${{ github.action_path }}/env/jdk/bin" >> $GITHUB_PATH
        echo "${{ github.action_path }}/env/maven/bin" >> $GITHUB_PATH
      shell: bash
    - name: "Check if Java is Available"
      id: check_java
      run: java -version
      shell: bash
    - name: "Check if Maven is Available"
      id: check_maven
      run: mvn -v
      shell: bash
